In [ ]:
import pandas as pd
import numpy as np

In [10]:
import pandas as pd

file_path = "../../data/Loan Eligibility Prediction.csv"

df = pd.read_csv(file_path)

df.head()

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,569,Female,No,0,Graduate,No,2378,0.0,9,360,1,Urban,N
1,15,Male,Yes,2,Graduate,No,1299,1086.0,17,120,1,Urban,Y
2,95,Male,No,0,Not Graduate,No,3620,0.0,25,120,1,Semiurban,Y
3,134,Male,Yes,0,Graduate,Yes,3459,0.0,25,120,1,Semiurban,Y
4,556,Male,Yes,1,Graduate,No,5468,1032.0,26,360,1,Semiurban,Y

In [7]:
import os

print(os.getcwd())

c:\Users\USER\Desktop\loan-approval-prediction\Loan-Approval-Prediction-Using-Machine-Learning\notebooks\notebooks

In [8]:
print("\nFiles and folders here:")
print(os.listdir())

Files and folders here:
['Member1_Data_Preprocessing.ipynb']

In [9]:
print("\nDoes ../data exist?")
print(os.path.exists("../data"))

Does ../data exist?
False

In [11]:
print("Dataset Shape:", df.shape)

Dataset Shape: (614, 13)

In [12]:
print("Column Names:")

for column in df.columns:
    print(column)

Column Names:
Customer_ID
Gender
Married
Dependents
Education
Self_Employed
Applicant_Income
Coapplicant_Income
Loan_Amount
Loan_Amount_Term
Credit_History
Property_Area
Loan_Status

In [13]:
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         614 non-null    int64
 1   Gender              614 non-null    str
 2   Married             614 non-null    str
 3   Dependents          614 non-null    int64
 4   Education           614 non-null    str
 5   Self_Employed       614 non-null    str
 6   Applicant_Income    614 non-null    int64
 7   Coapplicant_Income  614 non-null    float64
 8   Loan_Amount         614 non-null    int64
 9   Loan_Amount_Term    614 non-null    int64
 10  Credit_History      614 non-null    int64
 11  Property_Area       614 non-null    str
 12  Loan_Status         614 non-null    str
dtypes: float64(1), int64(6), str(6)
memory usage: 77.8 KB

In [14]:
df.describe(include="all")

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
count,614.000000,614,614,614.000000,614,614,614.000000,614.000000,614.000000,614.000000,614.000000,614,614
unique,NaN,2,2,NaN,2,2,NaN,NaN,NaN,NaN,NaN,3,2
top,NaN,Male,Yes,NaN,Graduate,No,NaN,NaN,NaN,NaN,NaN,Semiurban,Y
freq,NaN,499,399,NaN,480,523,NaN,NaN,NaN,NaN,NaN,233,422
mean,307.500000,NaN,NaN,0.856678,NaN,NaN,5403.459283,1621.245798,142.022801,338.892508,0.850163,NaN,NaN
std,177.390811,NaN,NaN,1.216651,NaN,NaN,6109.041673,2926.248369,87.083089,69.716355,0.357203,NaN,NaN
min,1.000000,NaN,NaN,0.000000,NaN,NaN,150.000000,0.000000,9.000000,12.000000,0.000000,NaN,NaN
25%,154.250000,NaN,NaN,0.000000,NaN,NaN,2877.500000,0.000000,98.000000,360.000000,1.000000,NaN,NaN
50%,307.500000,NaN,NaN,0.000000,NaN,NaN,3812.500000,1188.500000,125.000000,360.000000,1.000000,NaN,NaN
75%,460.750000,NaN,NaN,2.000000,NaN,NaN,5795.000000,2297.250000,164.750000,360.000000,1.000000,NaN,NaN
max,614.000000,NaN,NaN,4.000000,NaN,NaN,81000.000000,41667.000000,700.000000,480.000000,1.000000,NaN,NaN

In [15]:
for column in df.columns:
    print(f"\n{column}:")
    print(df[column].unique())

Customer_ID:
[569  15  95 134 556 148 271  29 583 510 611 232  47 122 401 521 342  42
 191  85  98 155 437 404 284 208 371 448 522 313 591 188 209 221 416 430
 452 584 411 169 402   3 187 408 539 182 330 358  11 133 147 336 467 514
 567 588 333 340 379 397 610 219 183  32 132 344  43 165 490  18 194 283
  41 207 278 422 487 547  73  93 124 173 361 427 200 137 311 455 557 118
 479 175 429  46 138 318 598 286 201 250 270 275 454 582 126 301 474 110
 258 529 589   7  74 171 353 364 398 499 520 543  45  57 240 304 367 425
 456 491 508  56  72 161 332 465 469  62  87 287 542  17  37  51 106 146
 216 359 385 423 435 473 502 511 523 532 177 135 180 545 400 403 549  21
  88 231 253 308 570 587 302 354 432 496  33 590 497 538 579 185 244 561
 576 609  12 399  28  40  78 296 329 375 414 424 447 468 470 493 527 533
 550 578 596  81 312 316 374 498  24  53 167 239 247 282 319 419  76 154
 199 300 386 394 395 472 482 501 517  14  34  20  99 257 276 289 321 406
 407  23  65 176 179 222 356 331 115 151 457 495   4  30  49  52  61 108
 159 186 195 198 206 233 241 246 264 288 317 376 393 566 163 426  27  94
 144 238 245 249 518 568 205 280 322 368 505  16  69 150 345 390 451 535
  67 273 348 536 210 220 292   2 212 225 260 265 381 384 462 483 544 603
 140 168  80 214 327 355 363 377 378 380 446 530  91 100 218 486 303 324
 387 464 478 555 564  19 101 366 428 614  44  54 262 293  58 204 217 269
 298 307 396  70  86 111 272 389 459 577  97 123 215 248 227 252 420 421
 440 504 112 291 235 242 305 466 541   5 365 594 294 434  38  48  50  60
 223 314 548 585 443 513 453 267 274 431 449 476 516 575  25 102 266 299
 113 152 347 409 444 463 117 481 243 263 320 372 546 602 383 540 608   8
 164 229 281 343 553 315 105 129 157 193 268 337 346 412 417 460 461 489
 528 580 471 475 559 192  63 357 572 202  83   9 142 189 196 226 236  71
 295 586 604 341 458 607  90 119 143 224 369 445  77 338 415  59  79 121
 181 442 599 554 130 166 335 560  39 328 116 141 310 391 519 492 571  75
 145 158 174 197 290 350 439 441 574 597 613  92 190 509 450  26 255 600
 125 405 534  13 170 230 297 360  31 251 581 592 277 503 500  89 228 563
 211 109 531 413 107 149 494 351 477 484 362 418 213 139 506 153 485 512
 612 160 237 256  66 565 120 349 184 558 595  84   6 162 392 573 254 234
  55 136 593 382 325 259 352 515  68  22  35 537 261  10 601 410 127 326
 373 526 433 279 309 507 524 334 178 605 488 370 156 562 131 172   1  36
  64  82  96 103 104 114 128 203 285 306 323 339 388 436 438 480 525 551
 552 606]

Gender:
<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

Married:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Dependents:
[0 2 1 4]

Education:
<ArrowStringArray>
['Graduate', 'Not Graduate']
Length: 2, dtype: str

Self_Employed:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Applicant_Income:
[ 2378  1299  3620  3459  5468  1538  3237  1442  3166 13262  4106  3716
  5649  4166  2889  2192  1800  4885  3988  1977  3254  1926  1963  1811
  3975 15759  3539  2500  2507  3000  2383  2479  2221  2995  2717  1958
  1880  3867  2237  2755  2178  2213  2917  1916  3875  3200  2718 14866
  5503  2947  2130  3333  2165  2833  4160  3069  3180  2900  5000  4600
  3167  2014  3173  2400  9323  2435  3510  3858  2301  3600  3244  3103
  2720  3547  3358  3500  3273  2957  3522  4723  4606 11000  4583  7085
  2667  2214 16667  4344  2920  3410  3316  2058  2987  3158  2600  1809
  2876  3900  2483  1836  3692  2071  5250  2679  4750  2333  4755  1820
  2666  3013  3033  2895  3400  3652  4695  2132  3315  1625 14880  3859
  2699  3583  2708  1875  1863  2935   210  3029  2138  3596  1828  1928
  3052  2330  3850  4566  3750  4691  3159  3598  5677  4281  2045  4895
  3017  1500  7660  2491  2583  2297  2875  5500  6500  3326  4692  2726
  3617  1782  3625  6250  3675  3232  3902  4226  3748  1000  4416  4333
  2764  2253  7250  4652 16692  3691  3775  3588  2785  3229  3833  3846
  2927  3399  3062  4625  3365  4230  3812  9703  3927  3541  1025  2281
  3416  3667  1993  3100  2653  3095   645  2031  1853  4188  6045  2750
  4124  4547  2167  3497  4009  3813  4384  5050  6277  4301  3597  2645
  3086  7333  2980 39147  4191  1907  4408  3189  5819  6050  7200  3704
  3717  4817  4467  3089  2799  4133  2698  3463  3406  2882  3074  3917
  4100  4342  5124  3814  4950  7100  4860  5488  2309 18165  3083  2550
  3418  4283  4400  3430  4931  5166  7167  7740  2083  2239  5703  4200
  2439  4917  2423  8750  4310  5391  3466  6783  2958  1759  3727  2346
  5191  2873  3593  5800  4887  4288  6216  5935  3941  4616  2060  3153
  3366   150  4666  3762  3276  4300  2366  5316 11146  4354  3087  2484
  2137  6608  4735  3427  3246  5829  7142  4050  2929  3075  3155  2510
  4000  6000  4608  6822  5417  2425  5821  3357  2971  5746  2526  2787
  4707  3283  3948  4708  2620  8624  3340 16525  6406  4843  4095  3572
  2577  3523  8300 37719  3015  4350  2965  3481 10000  5185  2768  2894
  6417  3987  3036  4167  4758  4053  4554  2473  3816 10513  6033  2499
  6256  8334  5285  3182  3450  5532  3887 12000  2609  8333  5116  4923
  1378  4006   674  3125  3250  3208  3676  2647  3708  5695  5568  6950
  7578  6325  2149  8080  5667  6400  7901  9963  2454  6080  3707  9833
  4180  5818 14583  5042  7667  9167  4683  5333  3417  5266 11757  9538
  5708  9508  2625 10416  3660  6125  6383  7583  9328  2769  9560 16250
  5780  7441 11250  3073  8000  6875  5167  1668  6540  3993  4865  6283
  8566  5923  3800  6096 11417 17263  9083  6700 10833  1600  7787 14999
  9166  6065  8072  5726  8799 10408  6333 33846 10139 16120  7933  9504
 16666  2661 11500  9357  5941 15000 14683  5815 10750  5955 12500  6133
  6083 12841   416 81000 23803  8666 17500 12876 20233 20833  7948 63337
  5516 18333 19730 39999 19484 20166 51763  5849  2275  4945  2395  6782
 13650  7451  3865  3992 20667  2000  3601  1830  3010 10047  4680  6633
  2492]

Coapplicant_Income:
[0.00000000e+00 1.08600000e+03 1.03200000e+03 1.42500000e+03
 1.74200000e+03 1.21300000e+03 9.97000000e+02 1.85100000e+03
 1.66600000e+03 2.53100000e+03 1.37600000e+03 3.41600000e+03
 2.13800000e+03 1.45600000e+03 5.36000000e+02 5.06300000e+03
 7.00000000e+02 4.49000000e+03 1.66400000e+03 6.66600000e+03
 1.92900000e+03 9.85799988e+02 1.30000000e+03 1.82000000e+03
 1.62500000e+03 1.39800000e+03 2.25000000e+03 7.36000000e+02
 1.61200008e+01 3.50000000e+03 2.13400000e+03 3.05300000e+03
 2.50000000e+03 1.86800000e+03 1.56000000e+03 2.46600000e+03
 3.38370000e+04 2.93400000e+03 7.54000000e+02 1.30200000e+03
 1.51600000e+03 1.76900000e+03 2.08300000e+03 3.03300000e+03
 1.45900000e+03 1.59100000e+03 1.80300000e+03 2.78500000e+03
 1.16700000e+03 1.87500000e+03 1.04100000e+03 2.91700000e+03
 2.00000000e+03 1.71700000e+03 1.33000000e+03 1.64400000e+03
 1.03000000e+03 4.48600000e+03 9.83000000e+02 1.71900000e+03
 1.28700000e+03 1.42400000e+03 1.61900000e+03 1.45100000e+03
 6.63000000e+02 1.80000000e+03 2.00000000e+04 2.11800000e+03
 2.05400000e+03 2.16700000e+03 1.86300000e+03 2.06400000e+03
 1.52200000e+03 1.75000000e+03 9.13000000e+02 1.70000000e+03
 2.23200000e+03 2.42000000e+02 4.61000000e+02 1.95000000e+03
 1.84000000e+03 1.04000000e+03 1.66800000e+03 3.02200000e+03
 1.25000000e+03 2.45100000e+03 2.03300000e+03 1.66700000e+03
 2.01600000e+03 2.73900000e+03 2.40500000e+03 1.64000000e+03
 1.98700000e+03 2.85700000e+03 1.91700000e+03 8.00000000e+02
 2.77300000e+03 2.81600000e+03 2.92500000e+03 1.40000000e+03
 1.50000000e+03 3.68300000e+03 1.63200000e+03 2.84000000e+03
 1.84200000e+03 2.40000000e+03 1.91100000e+03 1.96400000e+03
 1.79300000e+03 2.15700000e+03 2.35800000e+03 3.44000000e+03
 3.79600000e+03 4.75000000e+03 2.36500000e+03 2.59800000e+03
 5.00000000e+03 4.33300000e+03 9.23000000e+02 2.11500000e+03
 1.28000000e+03 4.30000000e+03 2.25300000e+03 2.03400000e+03
 4.41700000e+03 1.84300000e+03 1.89000000e+02 1.48300000e+03
 8.30000000e+02 2.33000000e+03 1.25500000e+03 2.25400000e+03
 1.85700000e+03 2.16800000e+03 2.04200000e+03 2.38300000e+03
 1.50800000e+03 3.15000000e+03 2.52400000e+03 1.43000000e+03
 3.33300000e+03 2.16600000e+03 5.05000000e+02 2.33300000e+03
 4.99600000e+03 1.21000000e+03 2.90000000e+03 3.54100000e+03
 1.77500000e+03 2.43600000e+03 2.98500000e+03 1.60000000e+03
 1.87200000e+03 4.26600000e+03 3.26300000e+03 2.33600000e+03
 2.20900000e+03 2.20000000e+03 1.08300000e+03 4.84000000e+02
 2.41700000e+03 2.21000000e+03 2.30200000e+03 8.98000000e+03
 3.02100000e+03 1.41700000e+03 5.30200000e+03 2.41600000e+03
 1.77900000e+03 1.98300000e+03 2.84500000e+03 3.30000000e+03
 2.34000000e+03 2.27500000e+03 2.85900000e+03 2.79100000e+03
 1.78300000e+03 1.99300000e+03 2.03500000e+03 1.73300000e+03
 1.38700000e+03 2.22300000e+03 1.71000000e+03 1.01400000e+03
 3.42800000e+03 3.80600000e+03 3.44700000e+03 2.54100000e+03
 4.11400000e+03 3.75000000e+03 3.23000000e+03 2.18800000e+03
 2.28300000e+03 5.70100000e+03 2.79200000e+03 1.41100000e+03
 2.50400000e+03 1.44700000e+03 2.42600000e+03 1.22900000e+03
 3.25000000e+03 3.85000000e+03 1.81100000e+03 6.88000000e+02
 2.45800000e+03 4.08300000e+03 2.07900000e+03 4.64800000e+03
 2.66900000e+03 3.44900000e+03 3.16700000e+03 1.88100000e+03
 1.52600000e+03 5.29600000e+03 2.58300000e+03 1.26000000e+03
 3.06600000e+03 3.33400000e+03 3.00000000e+03 4.30100000e+03
 1.58700000e+03 2.56900000e+03 4.16700000e+03 2.14200000e+03
 1.01000000e+03 8.33300000e+03 4.60000000e+03 3.23700000e+03
 4.00000000e+03 2.66700000e+03 7.25000000e+03 1.83300000e+03
 3.16600000e+03 2.30600000e+03 7.21000000e+03 2.16000000e+03
 1.91500000e+03 1.13100000e+03 1.77400000e+03 5.62500000e+03
 6.25000000e+03 5.06400000e+03 1.00000000e+03 5.65400000e+03
 3.01300000e+03 1.54200000e+03 2.01400000e+03 8.10600000e+03
 3.36900000e+03 3.89000000e+03 3.27400000e+03 5.62400000e+03
 4.41600000e+03 1.69500000e+03 3.60000000e+03 5.50000000e+03
 1.12600000e+03 3.66700000e+03 2.00400000e+03 2.40000000e+02
 4.59500000e+03 4.58300000e+03 4.19600000e+03 7.10100000e+03
 7.75000000e+03 4.23200000e+03 2.10000000e+03 3.66600000e+03
 3.90600000e+03 4.25000000e+03 1.09680000e+04 4.16670000e+04
 4.98300000e+03 7.87300000e+03 6.66700000e+03 7.16600000e+03
 1.13000000e+04 5.26600000e+03 2.06700000e+03 3.58300000e+03
 1.59000000e+03 3.13600000e+03 1.12500000e+03 1.60300000e+03
 2.08700000e+03 2.37500000e+03 3.80000000e+03]

Loan_Amount:
[  9  17  25  26  30  35  36  40  42  44  45  46  47  48  50  53  54  55
  56  58  59  60  61  62  63  65  66  67  70  71  72  73  74  75  76  78
  80  81  83  84  85  86  87  88  89  90  93  94  95  96  97  98  99 100
 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 139 140 141 142 143 144 145 146 148 149 150 151 152 153 154 155
 156 157 158 159 160 161 162 164 165 166 167 168 170 172 173 175 176 178
 180 181 182 184 185 186 187 188 190 191 192 194 196 200 201 205 207 208
 209 210 211 214 216 218 225 228 230 234 236 239 240 242 243 244 246 250
 253 255 258 259 260 265 267 275 279 280 286 290 292 296 300 304 308 311
 312 315 320 324 330 349 350 360 370 376 380 400 405 436 480 490 495 496
 500 570 600 650 700  22  18  15  20  10]

Loan_Amount_Term:
[360 120 180 240 300 480  36  84  12  60]

Credit_History:
[1 0]

Property_Area:
<ArrowStringArray>
['Urban', 'Semiurban', 'Rural']
Length: 3, dtype: str

Loan_Status:
<ArrowStringArray>
['N', 'Y']
Length: 2, dtype: str

In [16]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 0
Duplicates after: 0

In [17]:
print("Missing Values:")

print(df.isnull().sum())

Missing Values:
Customer_ID           0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
Applicant_Income      0
Coapplicant_Income    0
Loan_Amount           0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [18]:
numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns

for column in numerical_columns:
    df[column] = df[column].fillna(
        df[column].median()
    )

In [19]:
categorical_columns = df.select_dtypes(
    include=["object"]
).columns

for column in categorical_columns:
    df[column] = df[column].fillna(
        df[column].mode()[0]
    )

C:\Users\USER\AppData\Local\Temp\ipykernel_13544\1121312401.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

In [20]:
print("Missing values after preprocessing:")

print(df.isnull().sum())

Missing values after preprocessing:
Customer_ID           0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
Applicant_Income      0
Coapplicant_Income    0
Loan_Amount           0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [21]:
target = "Loan_Status"

print(df[target].value_counts())

Loan_Status
Y    422
N    192
Name: count, dtype: int64

In [22]:
X = df.drop(columns=[target])
y = df[target]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (614, 12)
Target shape: (614,)

In [23]:
categorical_columns = X.select_dtypes(
    include=["object"]
).columns.tolist()

numerical_columns = X.select_dtypes(
    exclude=["object"]
).columns.tolist()

print("Categorical columns:")
print(categorical_columns)

print("\nNumerical columns:")
print(numerical_columns)

Categorical columns:
['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area']

Numerical columns:
['Customer_ID', 'Dependents', 'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Loan_Amount_Term', 'Credit_History']

C:\Users\USER\AppData\Local\Temp\ipykernel_13544\1970466158.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(

In [24]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

for column in X.select_dtypes(
    include=["object"]
).columns:

    X[column] = label_encoder.fit_transform(
        X[column]
    )

print("Feature encoding completed.")

Feature encoding completed.

C:\Users\USER\AppData\Local\Temp\ipykernel_13544\1959399600.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in X.select_dtypes(

In [25]:
y = y.map({
    "Y": 1,
    "N": 0
})

In [26]:
print("Encoded Features:")
display(X.head())

print("\nEncoded Target:")
print(y.head(10))

Encoded Features:

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area
0,569,0,0,0,0,0,2378,0.0,9,360,1,2
1,15,1,1,2,0,0,1299,1086.0,17,120,1,2
2,95,1,0,0,1,0,3620,0.0,25,120,1,1
3,134,1,1,0,0,1,3459,0.0,25,120,1,1
4,556,1,1,1,0,0,5468,1032.0,26,360,1,1

Encoded Target:
0    0
1    1
2    1
3    1
4    1
5    1
6    1
7    0
8    1
9    1
Name: Loan_Status, dtype: int64

In [27]:
print("Missing values in X:")

print(X.isnull().sum())

print("\nMissing values in y:")

print(y.isnull().sum())

Missing values in X:
Customer_ID           0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
Applicant_Income      0
Coapplicant_Income    0
Loan_Amount           0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
dtype: int64

Missing values in y:
0

In [28]:
X = X.drop(columns=["Customer_ID"])

print("Final feature columns:")
print(X.columns.tolist())

print("\nFinal shape:")
print(X.shape)

Final feature columns:
['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Loan_Amount_Term', 'Credit_History', 'Property_Area']

Final shape:
(614, 11)

In [29]:
print("Final X shape:", X.shape)
print("Final y shape:", y.shape)

print("\nFinal X:")
display(X.head())

print("\nFinal y:")
print(y.head())

Final X shape: (614, 11)
Final y shape: (614,)

Final X:

,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area
0,0,0,0,0,0,2378,0.0,9,360,1,2
1,1,1,2,0,0,1299,1086.0,17,120,1,2
2,1,0,0,1,0,3620,0.0,25,120,1,1
3,1,1,0,0,1,3459,0.0,25,120,1,1
4,1,1,1,0,0,5468,1032.0,26,360,1,1

Final y:
0    0
1    1
2    1
3    1
4    1
Name: Loan_Status, dtype: int64

In [31]:
processed_df = X.copy()
processed_df["Loan_Status"] = y

processed_df.to_csv(
    "../../data/processed_loan_data.csv",
    index=False
)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.